name: Publish Production Image
on:
  push:
    paths:
      - "assets/**"
      - "client/**"
      - "server/**"
      - "nginx/**"
      - "*.js"
      - "*.json"
      - "Dockerfile"
      - "entrypoint.sh"
    tags:
      - "v*"

jobs:
  push_latest_to_registry:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            shaneisrael/snapsmaps

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            shaneisrael/snapsmaps:latest
          labels: ${{ steps.meta.outputs.labels }}
